apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ecoa-app
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/lijomadassery/ecoa.git
  ref:
    branch: main
  secretRef:
    name: flux-gitops-key
