apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ecoa-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: ecoa-app
  targetNamespace: my-app 