apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      volumes:
      - name: custom-ca
        configMap:
          name: zscaler-cert
      containers:
      - name: manager
        volumeMounts:
        - name: custom-ca
          mountPath: /etc/ssl/certs/custom
          readOnly: true 