apiVersion: v1
kind: Pod
metadata:
  name: github-test
  namespace: flux-system
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: alpine
    image: alpine:3.18
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsUser: 1000
      runAsNonRoot: true 